# Generated by Django 4.2.7 on 2025-01-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Islands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='core.islands')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('image', models.ImageField(upload_to='articles/')),
                ('uploaddate', models.DateField(auto_now_add=True)),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.subgoals')),
            ],
        ),
    ]
