# Generated by Django 4.2.7 on 2025-01-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_users_alter_articles_image_articles_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dream',
            field=models.TextField(default='개발자'),
        ),
    ]
