# Generated by Django 4.2.7 on 2025-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_users_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='islands',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
